version: "3.9"

services:
  backend:
    build: ./backend
    container_name: three-tier-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: mydb
      DB_PORT: 5432

  frontend:
    build: ./frontend
    container_name: three-tier-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://backend:5000

  postgres:
    image: postgres:15.14
    container_name: three-tier-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
